
ENV['COCOAPODS_DISABLE_STATS'] = "true"

target 'Kogatana' do
  pod 'Kogatana', :path => '../'

  target 'Kogatana_Tests' do
    inherit! :search_paths

    pod 'Specta'
  pod 'Expecta'
  end
end

target 'Kogatana_OSX' do
    pod 'Kogatana', :path => '../'
end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        if target.name == "Kogatana"
            target.build_configurations.each do |config|
                config.build_settings['GCC_TREAT_WARNINGS_AS_ERRORS'] = 'YES'
                #config.build_settings['WARNING_CFLAGS'] ||= '-Wno-error=deprecated-declarations'
            end
        end
    end
end
